#!/usr/bin/env python
# coding: utf-8

# # Supply Chain Analysis

# Supply Chain Analysis means analyzing varous components of a Supply Chain to understand how to improve the effectiveness of the
# Supply Chain to create more value for customers.

# In[1]:


import pandas as pd


# In[2]:


import plotly.express as px


# In[3]:


import plotly.io as pio


# In[4]:


import plotly.graph_objects as go


# In[5]:


pio.templates.default = "plotly_dark"


# In[6]:


data = pd.read_csv("supply_chain_data.csv")


# In[7]:


print(data.head())


# In[8]:


print(data.describe())


# In[9]:


fig= px.scatter(data, x='Price', y='Revenue generated',
                  color='Product type',
                  hover_data=['Number of products sold'],
                   trendline='lowess'
                   )


# In[10]:


fig.show()


# Here, we can see that the company derives more revenue from Skincare products,
# and the higher the price of skincare products, the more revenue they generate.

# In[11]:


sales_data = data.groupby('Product type')['Number of products sold'].sum().reset_index()

pie_chart = px.pie(sales_data, values='Number of products sold', names='Product type', title='Sales by product Type',
                   hover_data=['Number of products sold'],
                   hole = 0.5)
pie_chart.update_traces(textposition='inside', textinfo='percent+label')
pie_chart.show()


# From the above chart we can see that 45% of the business comes from skincare products, 29.5% from haircare and 25.5% from
# cosmetics. 

# In[12]:


total_revenue = data.groupby('Shipping carriers')['Revenue generated'].sum().reset_index()
fig = go.Figure()
fig.add_trace(go.Bar(x=total_revenue['Shipping carriers'],
                      y=total_revenue['Revenue generated']))
fig.update_layout(title='Total Revenue by Shipping Carrier',
                 xaxis_title='Shipping Carrier',
                 yaxis_title='Revenue Generated')
fig.show()


# So the company is using three carriers for transportation and Carrier B helps the company in generating more revenue.

# In[ ]:


avg_lead_time = data.groupby('Product type')['Lead time'].mean().reset_index()
avg_manufacturing_costs = data.groupby('Product type')['Manufacturing costs'].mean().reset_index()
result = pd.merge(avg_lead_time,avg_manufacturing_costs, on='Product type')
result.rename(columns={'Lead time': 'Average Lead Time', 'Manufacturing costs': 'Average Manufacturing Costs'}, inplace=True)
print(result)


# # Analyzing SKUs

# SKU stands for Stock Keeping Units. They are special codes that help companies keep track of all the different things they have
# for sale.

# In[13]:


revenue_chart = px.line(data, x='SKU',
                       y='Revenue generated',
                       title='Revenue Generated by SKU')

revenue_chart.show()


# In[15]:


stock_chart = px.line(data, x='SKU',
                     y='Stock levels',
                     title='Stock Levels by SKU')
stock_chart.show()


# Here in above chart, the stock levels refers to the number of products a store or business has in its inventory.

# In[16]:


order_quantity_chart = px.bar(data, x='SKU',
                             y='Order quantities',
                             title='Order Quantity by SKU')
order_quantity_chart.show()


# # Cost Analysis

# In[17]:


shipping_cost_chart = px.bar(data, x='Shipping carriers',
                            y='Shipping costs',
                            title='Shipping Costs by Carriers')
shipping_cost_chart.show()


# # Average Shipping Days

# In[14]:


ship_days = data.groupby('Shipping carriers')['Shipping times'].mean().reset_index()
# figure = go.Figure()
# figure.add_trace(go.Bar(x=ship_days['Shipping carriers'],
#                       y=ship_days['Shipping times']))
# figure.update_layout(title='Average Shipping Days',
#                  xaxis_title='Shipping Carriers',
#                  yaxis_title='Shipping Days')
figure = px.bar(ship_days, x='Shipping carriers', y='Shipping times',
               title='Average Shipping Days')
figure.show()


# # Transportation Mode

# In[18]:


transportation_cost = px.pie(data, 
                            values='Costs',
                            names='Transportation modes',
                            title='Cost Distribution by Transportation Mode',
                            hole=0.5)
transportation_cost.update_traces(textinfo='percent+label')
transportation_cost.show()


# From the above chart we can conclude that the company spends more on Road and Rail modes of transportation for the transportation of Goods.

# # Analyzing Defect Rate

# It refers to the precentage of products that have something wrong or are found broken after shipping.

# In[19]:


defect_rates = data.groupby('Product type')['Defect rates'].mean().reset_index()
fig = px.bar(defect_rates, x='Product type', y='Defect rates',
            title='Average Defect Rates by Product Type')
fig.show()


# In[20]:


pivot_table = pd.pivot_table(data, values='Defect rates',
                            index=['Transportation modes'],
                            aggfunc='mean')
print(pivot_table)
transportation_chart = px.pie(values=pivot_table["Defect rates"],
                             names=pivot_table.index,
                             title='Defect Rates by Transportation Mode',
                             hole=0.5)
transportation_chart.update_traces(textinfo='percent+label')
transportation_chart.show()


# Road Transportation results in a higher defect rate and Air transportation has the lowest defect rate.
